### ISSUE TITLE
[Bug]: AppImage crashing on fedora 41

### ISSUE THREAD

**Issue by mementomori74** [ThaUnknown/miru#597]
### Preflight checklist

- [X] I have searched the [issue tracker](https://github.com/ThaUnknown/miru/issues) for a bug report that matches the one I want to file, without success.
- [X] I have searched the [frequently asked questions](https://github.com/ThaUnknown/miru/blob/master/docs/faq.md) for a solution that fixes this problem, without success.
- [X] I have checked that I'm using the [latest stable](https://github.com/ThaUnknown/miru/releases/latest) version of the app.

### What app version are you using?

v5.5.9

### What operating system version are you using?

Linux

### Expected Behavior

On fedora 41 workstation (hyprland) appimages work fine. i loaded miru appimage in gear lever 

### Actual Behavior

the appimage crashes in gear lever so i downloaded a new version to different folder and same result

jvlist@fedora] - [~/Downloads] - [ma dec 09, 22:11]
└─[$] <> ./linux-Miru-5.5.9.AppImage
Checking for update
(node:7050) UnhandledPromiseRejectionWarning: TypeError: Object has been destroyed
    at A.destroy (/tmp/.mount_linux-pI4E7R/resources/app.asar/build/main.js:2:11659)
    at BrowserWindow.<anonymous> (/tmp/.mount_linux-pI4E7R/resources/app.asar/build/main.js:2:9165)
    at BrowserWindow.emit (node:events:531:35)
(Use `miru --trace-warnings ...` to show where the warning
 was created)
(node:7050) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
┌─[jvlist@fedora] - [~/Downloads] - [ma dec 09, 22:12]
└─[$] <> ./linux-Miru-5.5.9.AppImage --trace-warnings
Checking for update
(node:8056) UnhandledPromiseRejectionWarning: TypeError: Object has been destroyed
    at A.destroy (/tmp/.mount_linux-fpujWS/resources/app.asar/build/main.js:2:11659)
    at BrowserWindow.<anonymous> (/tmp/.mount_linux-fpujWS/resources/app.asar/build/main.js:2:9165)
    at BrowserWindow.emit (node:events:531:35)
    at emitUnhandledRejectionWarning (node:internal/process/promises:298:15)
    at warnWithErrorCodeUnhandledRejectionsMode (node:internal/process/promises:406:5)
    at processPromiseRejections (node:internal/process/promises:470:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(node:8056) TypeError: Object has been destroyed
    at A.destroy (/tmp/.mount_linux-fpujWS/resources/app.asar/build/main.js:2:11659)
    at BrowserWindow.<anonymous> (/tmp/.mount_linux-fpujWS/resources/app.asar/build/main.js:2:9165)
    at BrowserWindow.emit (node:events:531:35)

### Screenshots

![afbeelding](https://github.com/user-attachments/assets/b6b0d97d-d7ad-4921-8c4d-4359ea70079e)

**Comment by ThaUnknown** [comment]
your DWM crashes the renderer/gpu process, you should probably fix that yourself

**Comment by mementomori74** [comment]
ok will try to do that. im new on fedora and hyprland so i have to do some reading

**Comment by mementomori74** [comment]
So far nothing. all other appimages work fine. i tested gearlever and it launched but after reboot i get the same error again

**Comment by mementomori74** [comment]
after trying a gnome session, the appimage works fine. So the problem is in Hyprland i guess. after switching back to hyprland the image launched fine.
